export const CATEGORY_EDIT_TEXT = 'CATEGORY_EDIT_TEXT';
export const CATEGORY_ADD_CATE = 'CATEGORY_ADD_CATE';
export const CATEGORY_CLEAR_TEXT = 'CATEGORY_CLEAR_TEXT';
export const CATEGORY_DELETE_CATE = 'CATEGORY_DELETE_CATE';
