export const ORDER_BY_PRIORITY_DESC = 'ORDER_BY_PRIORITY_DESC';
export const ORDER_BY_PRIORITY_ASC = 'ORDER_BY_PRIORITY_ASC';
export const ORDER_BY_TIME_DESC = 'ORDER_BY_TIME_DESC';
export const ORDER_BY_TIME_ASC = 'ORDER_BY_TIME_ASC';
export const ORDER_BY_CATEGORY_DESC = 'ORDER_BY_CATEGORY_DESC';
export const ORDER_BY_CATEGORY_ASC = 'ORDER_BY_CATEGORY_ASC';

export const SET_ORDER_BY = 'SET_ORDER_BY';
