export const TASK_EDIT_TEXT = 'TASK_EDIT_TEXT';
export const TASK_EDIT_PRIORITY = 'TASK_EDIT_PRIORITY';
export const TASK_EDIT_CATEGORY = 'TASK_EDIT_CATEGORY';
export const TASK_EDIT_COLOR = 'TASK_EDIT_COLOR';
export const TASK_EDIT_DATE = 'TASK_EDIT_DATE';
